"""add source camera_type detection_interval to cameras

Revision ID: 3b5b70665f9a
Revises: 85b7438599a1
Create Date: 2026-05-14 07:49:24.851735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b5b70665f9a'
down_revision: Union[str, None] = '85b7438599a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    camera_type_enum = sa.Enum('CSI', 'RTSP', 'USB', name='camera_type_central_enum')
    camera_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('cameras', sa.Column('source', sa.String(length=500), nullable=True))
    op.add_column('cameras', sa.Column('camera_type', camera_type_enum, nullable=True))
    op.add_column('cameras', sa.Column('detection_interval', sa.Float(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'detection_interval')
    op.drop_column('cameras', 'camera_type')
    op.drop_column('cameras', 'source')
    # ### end Alembic commands ###
