"""add is_active to devices

Revision ID: 5774a60ff5d4
Revises: 3b5b70665f9a
Create Date: 2026-05-14 09:25:22.928365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5774a60ff5d4'
down_revision: Union[str, None] = '3b5b70665f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'is_active')
    # ### end Alembic commands ###
