"""add frame dimensions and snapshot path to cameras

Revision ID: 85b7438599a1
Revises: c807e2ed5c35
Create Date: 2026-05-14 07:21:00.847706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b7438599a1'
down_revision: Union[str, None] = 'c807e2ed5c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('frame_width', sa.Integer(), nullable=True))
    op.add_column('cameras', sa.Column('frame_height', sa.Integer(), nullable=True))
    op.add_column('cameras', sa.Column('snapshot_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'snapshot_path')
    op.drop_column('cameras', 'frame_height')
    op.drop_column('cameras', 'frame_width')
    # ### end Alembic commands ###
