"""make parking_slot zone_id nullable

Revision ID: a81161e2e1b0
Revises: b004c046598b
Create Date: 2026-06-25 10:34:39.164817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81161e2e1b0'
down_revision: Union[str, None] = 'b004c046598b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parking_slots', 'zone_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parking_slots', 'zone_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
