"""add polygon_coords to parking_slots

Revision ID: c807e2ed5c35
Revises: e879189d5a2e
Create Date: 2026-05-13 14:38:06.031140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c807e2ed5c35'
down_revision: Union[str, None] = 'e879189d5a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_slots', sa.Column('polygon_coords', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_slots', 'polygon_coords')
    # ### end Alembic commands ###
