"""add_slot_type_and_vehicle_type

Revision ID: e069085eb092
Revises: a1b2c3d4e5f6
Create Date: 2026-05-21 10:20:51.854753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e069085eb092'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_slots', sa.Column('slot_type', sa.String(length=20), nullable=False, server_default='GENERAL'))
    op.add_column('parking_slots', sa.Column('detected_vehicle_type', sa.String(length=20), nullable=True))
    op.add_column('slot_events', sa.Column('detected_vehicle_type', sa.String(length=20), nullable=True))
    op.add_column('slot_events', sa.Column('is_mismatched', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slot_events', 'is_mismatched')
    op.drop_column('slot_events', 'detected_vehicle_type')
    op.drop_column('parking_slots', 'detected_vehicle_type')
    op.drop_column('parking_slots', 'slot_type')
    # ### end Alembic commands ###
